config/routes.rb
Rails.application.routes.draw do
  resources :urls
  root to: "urls#new"  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :origin_url, presence: true
  
  # validates :origin_url, format: { with: /(http|https):\/\/,
  #   message: "only allows letters" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  require 'securerandom'
  def index
    @urls = Url.order('id DESC')
  end
  def new
    @url = Url.new
  end
  def create
    @url = Url.new(url_params)
    @url.shorten_url = SecureRandom.hex(6)
    if @url.save
      redirect_to urls_path
    else
      render :new
    end 
  end
  def show
    @url = Url.find_by(params[:shorten_url])
    redirect_to @url.origin_url
  end

  private
  def url_params
    params.require(:url).permit(:origin_url)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wubay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<h1>All</h1>
<table>
  <thead>
    <tr>
      <td>原網址</td>
      <td>縮短網址</td>
    </tr>
  </thead>
  <% @urls.each do |url| %>
    <tbody>
      <tr>
        <td><%= url.origin_url %></td>
        <td><%= "http://localhost:3000/urls/#{url.shorten_url}" %></td>
      </tr>
    </tbody>
  <% end %>
</table>

<%= link_to '返回產生器', "/"  %>
  

app/views/urls/new.html.erb
<h1>短網址產生器</h1>
<%= form_with model: @url  do |form| %>
<%= form.text_field :origin_url %>
<%= form.submit "短網址" %>  
<% end %>

app/views/urls/show.html.erb
<h1>show</h1>
<div><%= "http://localhost/3000/url/#{@url[:shotern_url]}" %></div>
<div><%= link_to "重新產生", new_url_path %></div>
  